package autonomousIO;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;

import wrapper.*;

/**
 * Dedicated to formatting the data for our autonomous data files.
 * @author Ghjf544912
 */
public class DataFormatter {
	
	/**
	 * @return The first line of data for each data file.
	 */
	public static String firstLine(){
		Date rhrn = new Date();
		SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
		
		return "Autonomous data file generated by the Patribots 4738 Stronghold 2016 rowboat"+dateFormat.format(rhrn);
	}
	
	/**
	 * @param encoders Encoders to grab information from.
	 * @return A line of data from the encoders to be written to the data file.
	 */
	public static String encoderData(HashMap<String,Encoder> encoders){
		String encoderData = "";
		for(int i = 0; i < encoders.size(); i++){
			encoderData += ((Encoder)(encoders.values().toArray()[i])).getSpeed() + ",";
		}
		encoderData.substring(encoderData.length()-2);
		return encoderData;
	}
	
	/**
	 * @author Ghjf544912
	 * @deprecated
	 * @param xbox
	 * @return
	 */
	public String controllerData(XboxController xbox){
		return xbox.toString();
	}
	
}
